// Script to fix wallet address mismatch
// This updates the .env file to use the correct Ganache deterministic account

const fs = require('fs');
const path = require('path');

// Ganache deterministic accounts (--deterministic flag)
// These are the default accounts generated by Ganache with the --deterministic flag
const GANACHE_ACCOUNTS = [
  {
    address: '0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1',
    privateKey: '0x4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d'
  },
  {
    address: '0xFFcf8FDEE72ac11b5c542428B35EEF5769C409f0',
    privateKey: '0x6cbed15c793ce57650b9877cf6fa156fbef513c4e6134f022a85b1ffdd59b2a1'
  },
  // Add more if needed
];

const envPath = path.join(__dirname, '..', '.env');

console.log('🔧 Fixing wallet address mismatch...\n');

// Read current .env file
let envContent = fs.readFileSync(envPath, 'utf8');

// Extract current values
const currentPrivateKey = envContent.match(/PRIVATE_KEY=(.*)/)?.[1] || '';
const currentContractAddress = envContent.match(/CONTRACT_ADDRESS=(.*)/)?.[1] || '';

console.log('📋 Current Configuration:');
console.log(`   PRIVATE_KEY: ${currentPrivateKey}`);
console.log(`   CONTRACT_ADDRESS: ${currentContractAddress}\n`);

// Update to use the first Ganache account (which deployed the contract)
const newPrivateKey = GANACHE_ACCOUNTS[0].privateKey;

console.log('✅ New Configuration:');
console.log(`   PRIVATE_KEY: ${newPrivateKey}`);
console.log(`   Wallet Address: ${GANACHE_ACCOUNTS[0].address}`);
console.log(`   CONTRACT_ADDRESS: ${currentContractAddress} (unchanged)\n`);

// Replace the private key in .env
envContent = envContent.replace(
  /PRIVATE_KEY=.*/,
  `PRIVATE_KEY=${newPrivateKey}`
);

// Write back to .env
fs.writeFileSync(envPath, envContent, 'utf8');

console.log('✅ .env file updated successfully!');
console.log('\n⚠️  IMPORTANT: Restart your backend server for changes to take effect.');
console.log('   Run: npm start\n');
